### ISSUE TITLE
Workerlist display bug

### ISSUE THREAD

**Issue by ErikHedblom** [pbl/skanken#23]
Everytime i use the *worker list* button the page fails to render correctly but if I refresh the page (F5) or go to the page using the URL it renders correctly. See **figure 1** and **3** for incorrectly reverend pages and **figure 2** and **4** for how they are supposed to look.

I have reproduced this in both chrome and IE. Can anyone else reproduce this? Too me this seems like a very strange error.

![workers](https://cloud.githubusercontent.com/assets/776846/7481792/1758c1fe-f373-11e4-8b9b-978f585be38b.png) **Figure 1**
![workersc](https://cloud.githubusercontent.com/assets/776846/7481793/176e9312-f373-11e4-8743-43b5b3778e1f.png)**Figure 2**
![no workers](https://cloud.githubusercontent.com/assets/776846/7481794/177793c2-f373-11e4-8674-9417e1893b83.png)**Figure 3**
![noworkersc](https://cloud.githubusercontent.com/assets/776846/7481795/17795eb4-f373-11e4-8a05-e4e9c730f458.png)**Figure 4**

**Comment by pbl** [comment]
this seems to have with the order the jquery data table javascript is run in the code. A dirty quick fix is to have the same jquery data table code in both the assetts/javascripts/application.js file and the members/_table.html.erb.

**Comment by pbl** [comment]
Solved in commit 218
