### ISSUE TITLE
Worker list filtering

### ISSUE THREAD

**Issue by ErikHedblom** [pbl/skanken#24]
I think the worker list filtering option need to be moved or highlighted in someway. 

Right now it's located at the bottom right corner which is not very intuitive. Also the default value in the menu is blank which makes it even harder to spot.

Another alternative could be to remove the feature since the search function seams to work rally well.

**Comment by pbl** [comment]
I agree. But it would be nice to have a filter select button especially for mobile users. I don't think reordering the filter button should be very hard
